name: OpenWrt-N1-基础版_by_gd0772

on:
  repository_dispatch:
  release:
    types: published
#  push:
#    branches:
#      - main
#    paths:
#      - 'all.config'
  schedule:
    - cron: 0 00 * * *
  watch:
    types: started
jobs:

  build_openwrt:

    name: OpenWrt_Build 

    runs-on: ubuntu-20.04

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: 准备环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5 libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "Asia/Shanghai"
      - name: 修改配置
        run: |
          git clone https://github.com/gd0772/package package/diy
          ./scripts/feeds update -a
      - name: 更新配置
        run: |
          curl -fsSL https://raw.githubusercontent.com/gd0772/diy/main/n1.sh | sh
          ./scripts/feeds install -a
          chmod -R 755 .
      - name: 导入配置
        run: |
          curl -fsSL https://raw.githubusercontent.com/gd0772/diy/main/N1/N1.jcb.sfe.config > .config
          make defconfig
      - name: 预下载dll
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
      - name: 编译固件
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: 打包整理
        run: |
         mkdir -p ./new/firmware
          mkdir -p ./new/package
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./new/package
          find bin/targets/ -name "*rootfs*tar.gz*" | xargs -i mv -f {} ./new/firmware
          cd ./new/firmware
          gzip *.*
      - name: 上传固件
        uses: actions/upload-artifact@main
        with:
          name: gd772_OpenWrt_N1-Mini
          path: ./new/firmware
      - name: 固件上传到 WeTransfer
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet -s -p 16 --no-progress ./new/firmware 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
